#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a52sxq

PRODUCT_COPY_FILES += \
    vendor/samsung/a52sxq/proprietary/recovery/root/vendor/firmware/tsp_stm/fts5cu56a_a52sxq.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/tsp_stm/fts5cu56a_a52sxq.bin \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/ODM/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Bluetooth_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/ODM/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/General_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/ODM/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Global_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/ODM/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Handset_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/ODM/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Hdmi_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/ODM/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Headset_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/ODM/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Speaker_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/ODM/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/workspaceFile.qwsp \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/OPEN/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Bluetooth_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/OPEN/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/General_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/OPEN/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Global_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/OPEN/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Handset_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/OPEN/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Hdmi_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/OPEN/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Headset_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/OPEN/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Speaker_cal.acdb \
    vendor/samsung/a52sxq/proprietary/vendor/etc/audconf/OPEN/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/workspaceFile.qwsp \
    vendor/samsung/a52sxq/proprietary/vendor/etc/nfc/sec_s3nrn4v_hwreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nrn4v_hwreg.bin \
    vendor/samsung/a52sxq/proprietary/vendor/etc/nfc/sec_s3nrn4v_swreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nrn4v_swreg.bin \
    vendor/samsung/a52sxq/proprietary/vendor/etc/qdcm_calib_data_ss_dsi_panel_S6E3FC3_AMS646YD01_LO_FHD.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ss_dsi_panel_S6E3FC3_AMS646YD01_LO_FHD.xml \
    vendor/samsung/a52sxq/proprietary/vendor/etc/sensors/config/kodiak_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kodiak_ak991x_0.json \
    vendor/samsung/a52sxq/proprietary/vendor/etc/sensors/config/kodiak_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kodiak_lsm6dso_0.json \
    vendor/samsung/a52sxq/proprietary/vendor/etc/sensors/config/kodiak_stk31610_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kodiak_stk31610_0.json \
    vendor/samsung/a52sxq/proprietary/vendor/etc/sensors/config/lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0.json \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/bt_nvm_loading.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_nvm_loading.xml \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/nfc/sec_s3nrn4v_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/sec_s3nrn4v_firmware.bin \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/ois_mcu_stm32g_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_mcu_stm32g_fw.bin \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/tsp_stm/fts5cu56a_a52sxq.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tsp_stm/fts5cu56a_a52sxq.bin \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev10/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev10/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev10/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev10/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev10/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev10/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev10/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev10/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev10/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev10/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev10/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev10/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev10/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev10/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev10/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev10/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev10/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev10/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev11/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev11/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev11/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev11/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev2/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev2/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev2/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev2/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev2/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev2/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev2/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev2/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev2/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev2/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev2/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev2/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev2/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev2/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev2/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev2/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev2/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev2/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev3/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev3/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev3/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev3/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev4/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev4/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev4/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev4/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev5/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev5/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev5/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev5/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev5/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev5/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev5/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev5/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev5/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev5/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev5/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev5/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev5/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev5/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev5/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev5/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev5/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev5/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev6/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev6/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev6/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev6/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev6/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev6/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev6/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev6/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev6/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev6/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev6/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev6/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev6/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev6/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev6/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev6/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev6/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev6/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev7/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev7/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev7/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev7/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev7/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev7/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev7/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev7/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev7/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev7/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev7/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev7/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev7/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev7/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev7/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev7/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev7/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev7/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev8/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev8/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev8/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev8/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev8/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev8/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev8/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev8/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev8/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev8/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev8/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev8/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev8/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev8/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev8/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev8/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev8/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev8/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev9/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev9/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev9/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev9/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev9/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev9/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev9/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev9/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev9/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev9/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev9/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev9/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev9/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev9/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev9/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev9/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528b/rev9/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528b/rev9/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev1/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev1/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev1/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev1/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev2/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev2/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev2/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev2/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev3/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev3/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev3/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev3/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev3/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev3/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev3/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev3/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev3/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev3/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev3/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev3/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev3/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev3/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev3/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev3/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev3/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev3/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev4/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev4/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev4/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev4/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev4/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev4/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev4/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev4/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev4/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev4/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev4/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev4/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev4/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev4/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev4/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev4/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev4/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev4/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev5/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev5/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev5/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev5/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev5/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev5/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev5/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev5/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev5/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev5/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev5/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev5/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev5/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev5/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev5/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev5/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev5/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev5/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev6/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev6/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev6/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev6/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev6/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev6/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev6/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev6/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev6/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev6/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev6/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev6/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev6/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev6/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev6/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev6/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev6/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev6/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev7/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev7/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev7/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev7/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev7/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev7/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev7/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev7/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev7/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev7/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev7/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev7/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev7/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev7/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev7/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev7/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wlan/a528n/rev7/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/a528n/rev7/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b00 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b01 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b02 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b03 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b04 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b05 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b06 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b07 \
    vendor/samsung/a52sxq/proprietary/vendor/firmware/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.mdt \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1p.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1p.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1p_otp.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_0_lsi_s5kgw1p_otp.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_1_sony_imx682.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_1_sony_imx682.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.13_0_lsi_s5kgd2_full.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.13_0_lsi_s5kgd2_full.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.13_0_lsi_s5kgd2_full_otp.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.13_0_lsi_s5kgd2_full_otp.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.13_1_sony_imx616_full.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.13_1_sony_imx616_full.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.1_0_lsi_s5kgd2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.1_0_lsi_s5kgd2.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.1_0_lsi_s5kgd2_otp.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.1_0_lsi_s5kgd2_otp.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.1_1_sony_imx616.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.1_1_sony_imx616.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.2_lsi_s5k3l6.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.2_lsi_s5k3l6.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.3_lsi_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.3_lsi_gc5035.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.4_lsi_gc5035_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.4_lsi_gc5035_macro.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_gc5035.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_gc5035_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_gc5035_macro.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5k3l6.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5k3l6.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5kgd2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5kgd2.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5kgw1p.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5kgw1p.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx616.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx616.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx682.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx682.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/f_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/f_dual_calibration.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/t_t10_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/t_t10_dual_calibration.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/uw_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/uw_dual_calibration.bin \
    vendor/samsung/a52sxq/proprietary/vendor/lib64/camera/w_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/w_dual_calibration.bin
